### ISSUE TITLE
English translation for the manual

### ISSUE THREAD

**Issue by sikmir** [dayanuyim/GisEditor#15]
Could you please translate the manual ([操作手冊](https://raw.githubusercontent.com/dayanuyim/GisEditor/master/manual.md)) into English?

> The Manual
> ========
> 1. [Map browsing](#sec_browsing)
> 2. [Waypoint editing](#sec_wpt)
> 3. [Track editing](#sec_trk)
> 4. [Output map screenshot](#sec_saveimg)
> 5. [Map overlay](#sec_maplist)
> 6. [Map grid](#sec_coordline)
>
> ...

**Comment by dayanuyim** [comment]
OK, maybe I could update it by the end of this week. :-)

**Comment by sikmir** [comment]
> Hi @sikmir ,
> I updated English manual in dev branch.
> https://github.com/dayanuyim/GisEditor/blob/dev/manual_en.md

Thanks! Now I can give it a try. Some GisEditor features look interesting (lightweight, free-hand track drawing, caching to mbtiles, custom map layers, etc).

Here is my comparison: [What are the best GPX (GPS eXchange Format) file editors?](https://www.slant.co/improve/topics/6721/~gpx-gps-exchange-format-file-editors)
 
> And it is surprising me there are non-Taiwan users.

Why not?;) Here is my first trying (Archlinux, [giseditor](https://aur.archlinux.org/packages/giseditor) AUR package have some issues):
```bash
$ crudini --set ~/.config/giseditor/giseditor.conf settings mapcache_dir /home/sikmir/.local/share/giseditor/mapcache
$ crudini --set ~/.config/giseditor/giseditor.user.conf settings trk_width 7
$ crudini --set ~/.config/giseditor/giseditor.user.conf settings fmt_pt_pos_coord latlon
$ crudini --set ~/.config/giseditor/giseditor.user.conf settings fmt_pt_pos_digits 6
$ mkdir -p ~/.local/share/giseditor/mapcache
$ ln -s /opt/giseditor/mapcache/OSM_Mapnik.xml ~/.local/share/giseditor/mapcache/OSM_Mapnik.xml
$ ln -s /opt/giseditor/mapcache/TF_OpenCycleMap.xml ~/.local/share/giseditor/mapcache/TF_OpenCycleMap.xml
$ cat << EOF > ~/.local/share/giseditor/mapcache/marshruty.ru.xml
<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
    <name>marshruty.ru</name>
    <minZoom>0</minZoom>
    <maxZoom>17</maxZoom>
    <tileType>png</tileType>
    <tileUpdate>None</tileUpdate>
    <url>https://maps.marshruty.ru/ml.ashx?x={$x}&amp;y={$y}&amp;z={$z}&amp;i=1&amp;al=1</url>
    <backgroundColor>#000000</backgroundColor>
</customMapSource>
EOF
$ cat << EOF > ~/.local/share/giseditor/mapcache/Maastokartta.xml
<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
    <name>Maastokartta (Topographic map)</name>
    <minZoom>0</minZoom>
    <maxZoom>17</maxZoom>
    <tileType>png</tileType>
    <tileUpdate>National Land Survey of Finland</tileUpdate>
    <url>https://retkikartta.fi/wmts/30c616a00f157e7357721900e8b0415c?SERVICE=WMTS&amp;REQUEST=GetTile&amp;VERSION=1.0.0&amp;LAYER=maastokartta&amp;STYLE=default&amp;TILEMATRIXSET=WGS84_Pseudo-Mercator&amp;TILEMATRIX={$z}&amp;TILEROW={$y}&amp;TILECOL={$x}&amp;FORMAT=image/png</url>
    <backgroundColor>#000000</backgroundColor>
</customMapSource>
EOF
$ sudo sed -i 's/GeoPoint(lon=121.334754, lat=24.987969)/GeoPoint(lon=30, lat=60)/' /opt/giseditor/main.py
```
Here is the result:
![giseditor-screenshot](https://user-images.githubusercontent.com/688044/48941067-1503c180-ef2b-11e8-9879-0793c8e0e9b0.png)
It looks promising. Thanks for your tool!

Some questions:
* Is it possible to set default location in config file? Instead of 121.334754 24.987969.

**Comment by dayanuyim** [comment]
Thanks for reminding,
I pushed the v0.27 tag. 
And I will have another issue for  default location.

I'm happy you like the tool.
Although the tool is to be free for non-commercial use, there are some components I need to check...
