### ISSUE TITLE
電力座標轉換

### ISSUE THREAD

**Issue by aki29** [dayanuyim/GisEditor#23]
請教
電力座標轉換TWD67 TM2該如何處理
可否分享資訊

感謝

**Comment by dayanuyim** [comment]
可以參考上河的超詳細解釋
https://www.sunriver.com.tw/grid_taipower.htm

實作可參考 [coord.py](https://github.com/dayanuyim/GisEditor/blob/master/src/coord.py), Line 373 的 electricToTWD67_TM2()
