### ISSUE TITLE
Linux start fail with bad event type keysym "Button3"

### ISSUE THREAD

**Issue by yanganto** [dayanuyim/GisEditor#4]
`ERROR:root:Startup failed: bad event type or keysym "Button3"`
- dev 1dd25e2bdaa3e17c3e07a16523c1507f88bdbbb9 
- Linux
- Python3.6
- KDE, Qtile (Both have the same problem)

**Comment by dayanuyim** [comment]
It's a typo of 'button-3'.
fix is commited to dev branch

**Comment by yanganto** [comment]
3Q
