### ISSUE TITLE
set config file in ~/.giseditor/conf in Linux environment

### ISSUE THREAD

**Issue by yanganto** [dayanuyim/GisEditor#5]
User ~/.giseditor/conf as default conf folder in Linux, Mac, and other *nix OS
The conf folder may be changed by options or arguments.

**Comment by yanganto** [comment]
@dayanuyim This issue is done. please merge. 3Q.

**Comment by dayanuyim** [comment]
1. I think it is good to change conf dir after configuring, better than just alter default conf. It diff the confs of system and user scope.
2. But **change_conf_dir (Line#163)** depends on that **app_conf (LIne#198)** and **user_conf (Line#261)** is ready. 
suggest: moving the 3 **'if blocks'** to the bottom of the script, and change their orders.
3. why not for **Windows**?
4. why not also copy **SYM_RULE_CONF**? 
    Then we can move back conf/bak/sym_rule.conf to conf/sym_rule.conf, as default conf.

**Comment by dayanuyim** [comment]
補充第4點，
一開始 sym_rule.conf 是放在 conf/ 下，可是我執行程式的時候會一直改到這個檔，改到repo； 
所以後來移到 conf/bak/，**第一次要用的時候再自己 copy 一份到 conf/ 下**。

我覺得讓 sym_rule.conf 也有一樣的機制，就可以解決這個不便了！
只需要把 sym_rule.conf 從 conf/bak/ 移回 conf/

**Comment by yanganto** [comment]
Thanks for your review
1. I am not sure what you mean. please explain more detail for me.
2. changed
3. Now is for Linux only
4. SYM_RULE_CONF will copy from sample when configure folder changing.

**Comment by dayanuyim** [comment]
我上了新的 commit ，你直接看 code 應該比較可以理解
1. 關於第2點，你本來的流程是對的，change_conf_dir 要在讀 conf之前。所以我改回本來的流程。
2. 程式第一次跑起來的時候 giseditor.conf 和 giseditor.app.conf 是不存在的，所以我加上檔案判斷。
3. 我把 for Linux 拿掉了，Windows/MAC應該都適用

**Comment by yanganto** [comment]
我剛測linux也沒問題，就把 feature branch 關掉了
